

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:



name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"    # Executa todo dia à meia-noite UTC (ajuste se quiser)
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake (SVG)
        uses: uses: Platane/snk/svg-only@v3

        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
  uses: crazy-max/ghaction-github-pages@v3.1.0
  with:
    target_branch: output
    build_dir: dist
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

